### PR TITLE
Merge sync with rustc 1.11.0-nightly (ec872dc8a 2016-06-07)

### PR DESCRIPTION
**Pull request by dtolnay**
#62

### CODE REVIEW

**Comment by dtolnay** [comment]
This fixes the issue that is breaking the rest of the PRs:

```
syntex_syntax/src/ext/base.rs:487:33: 487:62 error: lifetime parameter `'cx` declared on fn `ext::quote::expand_quote_item` appears only in the return type, but here is required to be higher-ranked, which means that `'cx` must appear in both argument and return types
syntex_syntax/src/ext/base.rs:487                                 ext::quote::expand_quote_item));
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
syntex_syntax/src/ext/base.rs:487:33: 487:62 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
syntex_syntax/src/ext/base.rs:487:33: 487:62 note: for more information, see issue #33685 <https://github.com/rust-lang/rust/issues/33685>
syntex_syntax/src/lib.rs:23:31: 23:39 note: lint level defined here
syntex_syntax/src/lib.rs:23 #![cfg_attr(not(stage0), deny(warnings))]
                                                          ^~~~~~~~
```

**Comment by erickt** [comment]
@humu: r+

**Comment by erickt** [comment]
@humu: r+ 27ea1e8

**Comment by dtolnay** [comment]
@homu r=erickt

**Comment by dtolnay** [comment]
I know why you got ignored (humu vs homu) but why did I get ignored?

**Comment by erickt** [comment]
Silly homu. Well it passed by travis so I'll just merge it myself.

**Pull request merged**
