### PR TITLE
Emit compiler diagnostics instead of panicking

### LINKED ISSUE #66: Registry.expand - avoid unwrap and possible panic?
method
https://github.com/serde-rs/syntex/blob/master/syntex/src/lib.rs#L126

panic here if any of the expanded modules contain syntax error:
https://github.com/serde-rs/syntex/blob/master/syntex/src/lib.rs#L135

rust parser itself provides result
https://github.com/rust-lang/rust/blob/44b3cd8c462a420ab64a44ef8f70c007001a1f44/src/libsyntax/parse/mod.rs#L73

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #66.

### CODE REVIEW

**Comment by dtolnay** [comment]
Before:

```
error: failed to run custom build command for `file:///github/serde/examples/serde-syntex-example v0.1.0`
Process didn't exit successfully: `/github/serde/examples/serde-syntex-example/target/debug/build/serde-syntex-example-9f0060ceb5920ffe/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "expected identifier, found `#`"', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

After:

```
error: failed to run custom build command for `serde-syntex-example v0.1.0 (file:///github/serde/examples/serde-syntex-example)`
Process didn't exit successfully: `/github/serde/examples/serde-syntex-example/target/debug/build/serde-syntex-example-9f0060ceb5920ffe/build-script-build` (exit code: 101)
--- stderr
error: expected identifier, found `#`
 --> src/main.rs.in:7:8
  |>
7 |> struct #
  |>        ^
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Parse', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by erickt** [comment]
@homu r+ 958493a

**Comment by erickt** [comment]
<3

**Comment by erickt** [comment]
Drat, one downside to this is that this'll leak the `syntex::Error` type through the `syntex::expand` method.   Think downstream projects should box up these error types so syntex doesn't leak?

**Pull request merged**
