### PR TITLE
Update syntex

### PR DESCRIPTION
**Pull request by pczarn**

### CODE REVIEW

**Comment by hansihe** [comment]
I am waiting for this to land. Are there any holdups?

**Comment by pczarn** [comment]
@hansihe: It seems @erickt is away.
For now, just run this in a chosen directory:

```
git clone -b rustup git@github.com:pczarn/syntex.git
git clone -b rustup-local git@github.com:pczarn/aster.git
git clone -b rustup-local git@github.com:pczarn/quasi.git
```

Then use a local path to depend on the updated version.

```
aster = { version = "0.9", path = "../aster/" }
```

I think cargo-vendor could make this process somehow easier.

**Comment by erickt** [comment]
Yeah, sorry traveling for the holidays, looking now!

**Pull request merged**
