### PR TITLE
Fix issue #120 and bump minor patch version 

### PR DESCRIPTION
**Pull request by keringar**

### CODE REVIEW

**Comment by dtolnay** [comment]
Please use the same fix that rustc used. I don't see this change in [`librustc_errors/emitter.rs`](https://github.com/rust-lang/rust/blob/b0a4074c5e87d24ff630f6aa456a64698bff3ed2/src/librustc_errors/emitter.rs#L1362).

**Comment by keringar** [comment]
I don't know how to test if rustc is fixed. Is there a way to use the internal library for testing? But just looking through the rustc code, it follows the same error path as syntex, ending with a call to panic.

**Comment by Dushistov** [comment]
@keringar @dtolnay  

Strange part that, if run such code in emacs eshell:
```

    let session = parse::ParseSess::new();
    let mut parser = parse::new_parser_from_source_str(&session,
                                                       "test code".into(),
                                                       "Boo Boo".into());
    if let Err(mut diagnostic) = parser.parse_crate_mod() {
        diagnostic.emit();
    }
```

it panics

> panicked at 'failed to emit error: operation not supported by the terminal'

But if run rustc in the same eshell:

```
/tmp $ cat boo.rs 
Boo Boo
/tmp $ rustc boo.rs 
error: expected one of `!` or `::`, found `Boo`
 --> boo.rs:1:5
  |
1 | Boo Boo
  |    -^^^ unexpected token
  |    |
  |    expected one of `!` or `::` here

error: aborting due to previous error
```

so no panics and all works as expected

**Comment by keringar** [comment]
I found out that rustc catches panics. So I'm going to mark this closed.

**Comment by Dushistov** [comment]
@keringar

Are you sure that problem in catch of panic? I replaced `term` crate used by `syntex_errors`
with `libterm` from `rustc/src/libterm`, and panic disappear.

**Pull request closed without merging**
