### PR TITLE
type renames MacroLoader -> Resolver, DummyMacroLoader -> DummyResolver

### PR DESCRIPTION
**Pull request by jchlapinski**
done to follow latest changes in nightly rust.

This change was done to fix aster compilation error on nightly 2016-09-15

### CODE REVIEW

**Comment by jchlapinski** [comment]
As a follow up I have made PR for syntex to rename the types as well there https://github.com/serde-rs/syntex/pull/93

**Comment by erickt** [comment]
I've been working on this, and it might be a little bit of time. There have also been a number of other upstream changes that we ought to land. Until landed I suggest sticking with the previous nightly.

**Comment by jchlapinski** [comment]
@erickt, are You planning to fix this particular issue otherwise, i.e. not renaming the types as I did? 
I think this issue should be resolved ASAP as a patch/hotfix, rather then wait for next larger release, especially since it may take a while and the fix is pretty much ready.

But anyway, please feel free to close this PR if You choose so.
Regards.

**Comment by erickt** [comment]
@jchlapinski: Well, this is going to take me a little bit to get the rebase working, so I'll trigger a release cycle with this now.

**Pull request merged**
